// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rOHg0NncsYcmLlpMDS1qu3H8USmNp48',
    appId: '1:349749381978:web:dbd39ab3289ef0c1744163',
    messagingSenderId: '349749381978',
    projectId: 'udmflutterproject',
    authDomain: 'udmflutterproject.firebaseapp.com',
    storageBucket: 'udmflutterproject.appspot.com',
    measurementId: 'G-G6J7RY4MQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAInWgHFV1d_SW-evwyS0rIcjFTp-dv86c',
    appId: '1:349749381978:android:44fd1cad179c8670744163',
    messagingSenderId: '349749381978',
    projectId: 'udmflutterproject',
    storageBucket: 'udmflutterproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwU2s2baGT76iw7i8tZQz0bKduCHnagE',
    appId: '1:349749381978:ios:0ab4c9ee439367e3744163',
    messagingSenderId: '349749381978',
    projectId: 'udmflutterproject',
    storageBucket: 'udmflutterproject.appspot.com',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwU2s2baGT76iw7i8tZQz0bKduCHnagE',
    appId: '1:349749381978:ios:2afe59621aa45a7b744163',
    messagingSenderId: '349749381978',
    projectId: 'udmflutterproject',
    storageBucket: 'udmflutterproject.appspot.com',
    iosBundleId: 'com.example.flutterFirestore.RunnerTests',
  );
}
